export const items = [
  "1. A dream you dream alone is only a dream. A dream you dream together is reality.",
  "2. Being deeply loved by someone gives you strength, while loving someone deeply gives you courage.",
  "3. Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment.",
  "4. Every moment is a fresh beginning.",
  "5. Everything you can imagine is real.",
  "6. Go confidently in the direction of your dreams! Live the life you've imagined.",
  "7. He who has a why to live can bear almost any how.",
  "8. I have no special talents. I am only passionately curious.",
  "9. In three words I can sum up everything I've learned about life: it goes on.",
  "10. It is never too late to be what you might have been.",
  "11. Life is really simple, but we insist on making it complicated.",
  "12. Life is what happens when you're busy making other plans.",
  "13. Life isn't about finding yourself. Life is about creating yourself.",
  "14. Limitations live only in our minds. But if we use our imaginations, our possibilities become limitless.",
  "15. No act of kindness, no matter how small, is ever wasted.",
  "16. The only impossible journey is the one you never begin.",
  "17. The only real mistake is the one from which we learn nothing.",
  "18. The purpose of our lives is to be happy.",
  "19. The true sign of intelligence is not knowledge but imagination.",
  "20 There is nothing permanent except change.",
  "21. To live is the rarest thing in the world. Most people exist, that is all.",
  "22. Turn your wounds into wisdom.",
  "23. We must not allow other people’s limited perceptions to define us.",
  "24. We must take change by the hand or rest assuredly, change will take us by the throat.",
  "25. What we think, we become.",
  "26. When you arise in the morning think of what a privilege it is to be alive, to think, to enjoy, to love...",
  "27. When you reach the end of your rope, tie a knot in it and hang on.",
  "28. Where there is love there is life.",
  "29. Whether you think you can or you think you can’t, you’re right.",
  "30. With the new day comes new strength and new thoughts.",
  "31. You are never too old to set another goal or to dream a new dream.",
  "32. You can't blame gravity for falling in love.",
  "33. You don't have to be great to start, but you have to start to be great.",
  "34. You miss 100% of the shots you don't take.",
  "35. You must be the change you wish to see in the world.",
  "36. Your big opportunity may be right where you are now.",
  "37. A champion is someone who gets up when they can't.",
  "38. All that we are is the result of what we have thought.",
  "39. An unexamined life is not worth living.",
  "40. Ask and it will be given to you; search, and you will find; knock and the door will be opened for you.",
  "41. Be yourself; everyone else is already taken.",
  "42. Believe you can and you're halfway there.",
  "43. Change your thoughts and you change your world.",
  "44. Do what you feel in your heart to be right – for you’ll be criticized anyway.",
  "45. Don't judge each day by the harvest you reap but by the seeds that you plant.",
  "46. Don't watch the clock; do what it does. Keep going.",
  "47. Ever tried. Ever failed. No matter. Try Again. Fail again. Fail better.",
  "48. Every strike brings me closer to the next home run.",
  "49. Happiness is not something ready made. It comes from your own actions.",
  "50. He who has health has hope; and he who has hope has everything.",
  "51. I attribute my success to this: I never gave or took any excuse.",
  "52. If you tell the truth, you don't have to remember anything.",
  "53. If you're going through hell, keep going.",
  "54. It is our choices that show what we truly are, far more than our abilities.",
  "55. Keep your face always toward the sunshine—and shadows will fall behind you.",
  "56. Life is 10% what happens to us and 90% how we react to it.",
  "57. Life is about making an impact, not making an income.",
  "58. Life is from the inside out. When you shift on the inside, life shifts on the outside.",
  "59. Love the life you live. Live the life you love.",
  "60. Many of life's failures are people who did not realize how close they were to success when they gave up.",
  "61. Never bend your head. Always hold it high. Look the world straight in the eye.",
  "62. No one can make you feel inferior without your consent.",
  "63. Only a life lived for others is a life worthwhile.",
  "64. Opportunity does not knock, it presents itself when you beat down the door.",
  "65. Peace begins with a smile.",
  "66. People who are crazy enough to think they can change the world, are the ones who do.",
  "67. Perfection is not attainable, but if we chase perfection we can catch excellence.",
  "68. Remember that not getting what you want is sometimes a wonderful stroke of luck.",
  "69. Set your goals high, and don't stop till you get there.",
  "70. Sometimes you can't see yourself clearly until you see yourself through the eyes of others.",
  "71. Start where you are. Use what you have. Do what you can.",
  "72. Success is not how high you have climbed, but how you make a positive difference to the world.",
  "73. The best way to predict the future is to invent it.",
  "74. The best preparation for tomorrow is doing your best today.",
  "75. The best time to plant a tree was 20 years ago. The second best time is now.",
  "76. The greatest glory in living lies not in never falling, but in rising every time we fall.",
  "77. The journey of a thousand miles begins with one step.",
  "78. The mind is everything. What you think you become.",
  "79. The most common way people give up their power is by thinking they don’t have any.",
  "80. The only limit to our realization of tomorrow is our doubts of today.",
  "81. The only place where success comes before work is in the dictionary.",
  "82. The only real failure in life is not to be true to the best one knows.",
  "83. The only thing worse than being blind is having sight but no vision.",
  "84. The only way to do great work is to love what you do.",
  "85. The purpose of life is not to be happy. It is to be useful, to be honorable, to be compassionate, to have it make some difference that you have lived and lived well.",
  "86. There are no secrets to success. It is the result of preparation, hard work, and learning from failure.",
  "87. There is only one happiness in this life, to love and be loved.",
  "88. Things work out best for those who make the best of how things work out.",
  "89. This above all: to thine own self be true.",
  "90. To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.",
  "91. We do not remember days, we remember moments.",
  "92. What lies behind us and what lies before us are tiny matters compared to what lies within us.",
  "93. What you get by achieving your goals is not as important as what you become by achieving your goals.",
  "94. When everything seems to be going against you, remember that the airplane takes off against the wind, not with it.",
  "95. Whenever you find yourself on the side of the majority, it is time to pause and reflect.",
  "96. Whether you think you can, or you think you can't–you're right.",
  "97. You can't help everyone, but everyone can help someone.",
  "98. Your task is not to seek for love, but merely to seek and find all the barriers within yourself that you have built against it.",
  "99. Difficult roads often lead to beautiful destinations. The best is yet to come.",
  "100. Strength does not come from physical capacity. It comes from an indomitable will.",
];
